### ISSUE TITLE
Modified/Update DateTime Properties

### ISSUE THREAD

**Issue by KallumTanton** [ticketsource/openapi-spec#1]
If each object returned a DateTime property showing when it was last updated/modified an external app can identify which objects it needs to update in it's internal data store.

Also, being able to add this as a request filter parameter would add some efficiency to update calls, e.g.:

`https://api.ticketsource.io/events/evt_123456/dates?modifiedFrom=2018-06-21T09:00:00+00:00`

**Comment by imaginax** [comment]
Can I add a "Me Too" to this request please. Trying to keep our CRM system in Synch with Orders and Customers... at the moment it looks like we need to poll *everything* every day and at 60 API requests a minute that's proving troublesome?

**Comment by cfreear** [comment]
Just a quick update on this request; this functionality is currently under development and we hope to have some more news to share soon!

**Comment by imaginax** [comment]
That's great to hear, thank you!

I don't suppose there's a chance to lift or raise the throttle limit for certain API keys in the meantime is there please? My ETL software's lowest setting is one request a second which in theory matches the 60 a minute but in practice the clocks aren't _100%_ in synch and you see that as 61 requests in a minute as often as not... causing my job to end meaning starting (what can be quite a long process) again.

**Comment by x2764tech** [comment]
Any movement on this?

**Comment by cfreear** [comment]
This is still on our development roadmap but is pending some additional changes we are in the process of making. We'll make sure to update this issue once it's available.

**Comment by cfreear** [comment]
`created_at` and `updated_at` properties are available on all resources (`updated_at` will return `null` if the resource has never been updated)

Further more you can filter these two fields (more to come!) by passing a filter parameter in your request, e.g.:
```
https://api.ticketsource.io/events?filter[created_at][operator]=after&filter[created_at][value]=2019-01-01
```
Read more in [our guide](https://ticketsource.io/getting-started#filtering)

**Comment by x2764tech** [comment]
@cfreear Thanks for this - it is going to be really useful.

One question related to the implementation:
What causes the `updated_at` properties to change? 
For example, if I get events with `updated_at` `after` `2019-05-17`, does this include events where the times or venues has changed?

**Comment by cfreear** [comment]
Currently `updated_at` for a resource will only change when that resource is modified, we are however looking at ways solutions to add the functionality you seek (most likely as an extra property along the lines of `children_updated_at` or even separate `venues_updated_at`, `dates_updated_at` etc.)
