### ISSUE TITLE
Ticket Prices

### ISSUE THREAD

**Issue by x2764tech** [ticketsource/openapi-spec#2]
Is there a way to get ticket prices from the API?
For example, [our event](https://www.ticketsource.co.uk/booking/select/UhVoBmdPtGqj) has tickets for 5GBP and 4GBP, but I can't seem to get this information from the API.
Thanks

**Comment by cfreear** [comment]
A price category end point is currently planned among other developments, we'll look at putting together a roadmap of planned enhancements to keep our users better informed.
