### ISSUE TITLE
500 Error on retrieving booking

### ISSUE THREAD

**Issue by imaginax** [ticketsource/openapi-spec#4]
Hello, I'm receiving a 500 error when retrieving bookings (from the SELF link from the booking when retrieving from dates). Example below:

`{
    "errors": [
        {
            "id": "s05f1b900b3694ae5bbd326fc7c8f807c",
            "links": {
                "about": "https://www.ticketsource.io/docs/errors/internal-server"
            },
            "status": 500,
            "code": "internal_server_error",
            "title": "Internal Server Error",
            "detail": "Something went wrong on our end, please contact TicketSource support quoting this ID: s05f1b900b3694ae5bbd326fc7c8f807c"
        }
    ]
}
`

Information that might be of help, we just started to add "Sundries" as an option so patrons can pre-book drinks (we're trying to make the Theatre Covid Secure). I'm guessing Sundries are line items attached to a Booking? I can't see another way to query them like the **seats** endpoint?

Many thanks, 
Mike

**Comment by cfreear** [comment]
Thanks for reporting this, I can confirm the issue has now been resolved. You should now be able to fetch line items for a booking (which include sundries!)
