### ISSUE TITLE
Event time values are one hour different (behind) from API

### ISSUE THREAD

**Issue by jamesmacwhite** [ticketsource/openapi-spec#6]
I've noticed that event times from the API are now being provided as one hour behind the set date in our TicketSource profile. For example an event that is set as:

Event start time: 7:00 PM
Event end time: 9:00 PM

Is being output in the API as:

start: 2022-03-31T18:00:00+00:00
end: 2022-03-31T20:00:00+00:00

It is the case for any datetime field however.

This is one hour different. TicketSource and our TicketShop profile is displaying the correct values, but the API isn't.

I suspect this might be related to BST handling, but it is being applied before BST is actually in effect. Your support team has indicated this is the case but there isn't really a solution and this happens every March? The problem I have with that is we are taking data from your API and would expect this to be correct, but it isn't and hence our website is now being coerced into displaying the wrong times on an event.

Can I get clarity on this issue at all, as it seems like this really is an API issue.

**Comment by cfreear** [comment]
Hi James

All dates returned via the TicketSource API are in UTC for consistency, in the UK BST begins on the last Sunday in March, this year (2022) it falls on 2022-03-27 so an event taking place at 7PM BST on March the 31st would have a date time of 2022-03-31T18:00:00+00:00 including the UTC offset of zero hours. The BST equivalent of this would be 2022-03-31T19:00:00+01:00 including the UTC offset of plus one hour.

We would recommend you use a datetime library to parse the dates you are receiving from the TicketSource API and display them in the specific timezone you require.

**Comment by jamesmacwhite** [comment]
Hi @cfreear 

Thanks for your reply. I did consider that these dates were UTC. However this hadn't been a problem up until now, but I assume it's because GMT and UTC are currently the same, so the BST change now shows up this problem.

The feed import process we use through Craft CMS (FeedMe) should be timezone aware for this case. It too stores dates in UTC in the database but should then output the configured timezone value on the front end, however it seems to have failed here, so I might need to look into that on our side.

Thanks for getting back to me though!

**Comment by cfreear** [comment]
It's not the first time GMT mirroring UTC has caused confusion around this, we might look into adding a reminder to our guide in the hopes it doesn't catch anyone else out in the future! Good luck tracking down the issue and please get back to us if you have any further queries.

**Comment by jamesmacwhite** [comment]
@cfreear Thanks for that. I think that would be helpful. Maybe adding to the API docs would be good to clarify date values are always UTC+00:00.

Maybe here: https://openapi.ticketsource.io/#tag/dates
