### ISSUE TITLE
Filtering events by properties like "activated" or "public"

### ISSUE THREAD

**Issue by jamesmacwhite** [ticketsource/openapi-spec#7]
Is there a way or as a future enhancement to filter events on properties like "activated" or "public".

An example of this being useful, if an event is not published or draft i,e. not finished but the basic event record exists, it will be returned in the list all events response. Ideally, you might want to ensure that only events that have been through all the event setup process and are ready for public promotion to be displayed i.e. for another source to import the data.

There could be workarounds to this i.e. mapping the activated and public values to a entry status or visibility setting so it wouldn't show up but still be imported.

At the moment it just seems the properties eligible for filtering are a little limited: https://www.ticketsource.io/working-with-events#events. It seems true/false filtering is possible, although the settled attribute is listed but doesn't seem to exist on the attributes documentation for an event.

**Comment by cfreear** [comment]
Hi James

The openapi spec and documentation are currently undergoing a rewrite and as such aren't completely up to date with the current functionality of the API, we hope to have these updates released shortly. Filtering on other boolean properties for an event is something we have planned for general release in the near future but I can check if this can be brought forward as you have a specific use case for it.

**Comment by jamesmacwhite** [comment]
@cfreear Hi, sorry for not responding to you immediately! Thank you for your response. That's good to hear regarding additional filtering. My main request is being able to basically filter out events that are classed as incomplete. We have hit a scenario with this when an event has been duplicated and our website imported it and assigned a slug value (generated off the title), which was a duplicate of another event. Even when the event title was changed before going live on TicketSource our website would not update the slug because it's generated by the title on the first import. If I could exclude incomplete events, this would have been avoided. So that's my wishlist, please let incomplete events be excluded from an API response via filter if possible!

**Comment by cfreear** [comment]
@jamesmacwhite I'm pleased to say you can now filter events on their `activated` (the one you would use), `archived` and `public` properties. We've updated the list of filters at https://www.ticketsource.io/working-with-events#events to reflect this.

**Comment by jamesmacwhite** [comment]
@cfreear Amazing! Thank you!

**Comment by jamesmacwhite** [comment]
Sorry, just on this what is the syntax for filtering on boolean, I'm looking at the docs, I thought this would be the syntax:

```
/events?per_page=10&filter[activated][eq]=true
```

But I'm getting a 400, so I'm making a mistake with the query string syntax

```
{
    "errors": [
        {
            "id": "tsHfIkVVqyJhoe4BoqPjQg4oH095KQtGV0",
            "links": {
                "about": "https://www.ticketsource.io/docs/errors/validation-failed"
            },
            "status": 400,
            "code": "validation_failed",
            "title": "Bad Request",
            "detail": "The filter.activated.operator field is required when filter.activated is present."
        }
    ]
}
```

Sorry if I'm missing something.

**Comment by jamesmacwhite** [comment]
Ah, got it, you need to chain the operator and value together:

```
/events?per_page=10&filter[activated][operator]=eq&filter[activated][value]=true
```

**Comment by cfreear** [comment]
Glad you got it figured out, we'll probably add some more examples to the docs in a future release as the nested object structure of the filter parameter can be a bit confusing in the context of a query string!

**Comment by jamesmacwhite** [comment]
Thank you! Yes a few examples in the docs would be great for others, it was the settled example in the docs that helped me figure out it's a two part filter process, rather than trying to do it as a single filter query param.
